### ISSUE TITLE
cannot run the code

### ISSUE THREAD

**Issue by Light--** [bruinxiong/Modified-CBAMnet.mxnet#2]
i used the code in this repo to replace the module used in mxnet Arcface code, but it cannot run. It reports out of memory error even i set batch_size to 2...

```
Traceback (most recent call last):
  File "train_parall_fc7.py", line 411, in <module>
    main()
  File "train_parall_fc7.py", line 408, in main
    train_net(args)
  File "train_parall_fc7.py", line 403, in train_net
    epoch_end_callback = epoch_cb )
  File "/home/user1/pjs/_chall_/arcface_cbam/recognition/parall_module_local_v1.py", line 494, in fit
    for_training=True, force_rebind=force_rebind)
  File "/home/user1/pjs/_chall_/arcface_cbam/recognition/parall_module_local_v1.py", line 226, in bind
    force_rebind=False, shared_module=None)
  File "/home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 375, in bind_exec
    shared_group))
  File "/home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 1629, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (2, 3, 112, 112)
softmax_label: (2,)
[13:14:51] src/storage/./pooled_storage_manager.h:157: cudaMalloc failed: out of memory
Stack trace:
  [bt] (0) /home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x4b04cb) [0x7f42436644cb]
  [bt] (1) /home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2e653eb) [0x7f42460193eb]
  [bt] (2) /home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2e6af0f) [0x7f424601ef0f]
  [bt] (3) /home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/libmxnet.so(mxnet::NDArray::NDArray(mxnet::TShape const&, mxnet::Context, bool, int)+0x5d0) [0x7f42456e56d0]
  [bt] (4) /home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/libmxnet.so(mxnet::common::EmplaceBackZeros(mxnet::NDArrayStorageType, mxnet::TShape const&, mxnet::Context const&, int, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*)+0x8c) [0x7f42457b43dc]
  [bt] (5) /home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::InitArguments(nnvm::IndexedGraph const&, std::vector<mxnet::TShape, std::allocator<mxnet::TShape> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, mxnet::Executor const*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*)+0x983) [0x7f42457b4dd3]
  [bt] (6) /home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::Init(nnvm::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::less<std::string>, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::unordered_map<std::string, mxnet::TShape, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::TShape> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, mxnet::Executor*, std::unordered_map<nnvm::NodeEntry, mxnet::NDArray, nnvm::NodeEntryHash, nnvm::NodeEntryEqual, std::allocator<std::pair<nnvm::NodeEntry const, mxnet::NDArray> > > const&)+0x6bc) [0x7f42457c332c]
  [bt] (7) /home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/libmxnet.so(mxnet::Executor::SimpleBind(nnvm::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::less<std::string>, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::unordered_map<std::string, mxnet::TShape, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::TShape> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, mxnet::Executor*)+0x8a8) [0x7f42457c4258]
  [bt] (8) /home/user1/miniconda3/envs/hardsample/lib/python2.7/site-packages/mxnet/libmxnet.so(MXExecutorSimpleBindEx+0x221b) [0x7f424570595b]
```

**Comment by Light--** [comment]
when calling the ```get_symbol() ``` function in ```train.py```, the parameters should be set to: ```config.emb_size,config.num_layers``` not ```config.num_classes,config.num_layers ```
```
embedding = eval(config.net_name).get_symbol(config.emb_size,config.num_layers)
```
otherwise, you will get hundreds of thousands of neurons in fc1 layer.

**Comment by bruinxiong** [comment]
@Light-- It can be applied in insightface but need to be modified in config for fitting the size of emb. The original one is trained without arcface loss.

**Comment by Light--** [comment]
> @Light-- It can be applied in insightface but need to be modified in config for fitting the size of emb. The original one is trained without arcface loss.

@bruinxiong  大哥，谢谢你的回复！用的arcface分类loss，cbam的论文好像没有特别提到他用的什么loss。。默认只用交叉熵？

但是发现这个效果不好啊。没有超过我的baseline
我用的18层cbam，训练样本87万，类别数10万，batch size 512，学习率0.1，每10、16、22个epoch衰减10%，训练了25个epoch，拿到的最好模型没有超过baseline resnet18。您能给指点指点么？

**Comment by bruinxiong** [comment]
@Light-- 我并未直接训练过18层cbam，100层的我早先训练过，效果相比resnet101能稍微好些。算法本身的实现和架构逻辑还是make sence的，只是需要去调参，和摸索一些技巧。你所说的baseline也是用的完全相同的设置和数据预处理方法？另外，数据量和类别数不算小，18层cbam本身模型容量的优势有没有发挥出来，导致欠拟合也有可能，你可以尝试更深的架构，多跑跑实验看看。
